#ifndef MISAKA_KEYS_H
#define MISAKA_KEYS_H

#define MISAKA_BUTTON_LEFT          0
#define MISAKA_BUTTON_RIGHT         1

#define MISAKA_KEY_UNKNOWN         -1
#define MISAKA_KEY_SPACE           32
#define MISAKA_KEY_APOSTROPHE      39
#define MISAKA_KEY_COMMA           44
#define MISAKA_KEY_MINUS           45
#define MISAKA_KEY_PERIOD          46
#define MISAKA_KEY_SLASH           47
#define MISAKA_KEY_0               48
#define MISAKA_KEY_1               49
#define MISAKA_KEY_2               50
#define MISAKA_KEY_3               51
#define MISAKA_KEY_4               52
#define MISAKA_KEY_5               53
#define MISAKA_KEY_6               54
#define MISAKA_KEY_7               55
#define MISAKA_KEY_8               56
#define MISAKA_KEY_9               57
#define MISAKA_KEY_SEMICOLON       59
#define MISAKA_KEY_EQUAL           61
#define MISAKA_KEY_A               65
#define MISAKA_KEY_B               66
#define MISAKA_KEY_C               67
#define MISAKA_KEY_D               68
#define MISAKA_KEY_E               69
#define MISAKA_KEY_F               70
#define MISAKA_KEY_G               71
#define MISAKA_KEY_H               72
#define MISAKA_KEY_I               73
#define MISAKA_KEY_J               74
#define MISAKA_KEY_K               75
#define MISAKA_KEY_L               76
#define MISAKA_KEY_M               77
#define MISAKA_KEY_N               78
#define MISAKA_KEY_O               79
#define MISAKA_KEY_P               80
#define MISAKA_KEY_Q               81
#define MISAKA_KEY_R               82
#define MISAKA_KEY_S               83
#define MISAKA_KEY_T               84
#define MISAKA_KEY_U               85
#define MISAKA_KEY_V               86
#define MISAKA_KEY_W               87
#define MISAKA_KEY_X               88
#define MISAKA_KEY_Y               89
#define MISAKA_KEY_Z               90
#define MISAKA_KEY_LEFT_BRACKET    91
#define MISAKA_KEY_BACKSLASH       92
#define MISAKA_KEY_RIGHT_BRACKET   93
#define MISAKA_KEY_GRAVE_ACCENT    96
#define MISAKA_KEY_WORLD_1         161
#define MISAKA_KEY_WORLD_2         162
#define MISAKA_KEY_ESCAPE          256
#define MISAKA_KEY_ENTER           257
#define MISAKA_KEY_TAB             258
#define MISAKA_KEY_BACKSPACE       259
#define MISAKA_KEY_INSERT          260
#define MISAKA_KEY_DELETEA         261
#define MISAKA_KEY_RIGHT           262
#define MISAKA_KEY_LEFT            263
#define MISAKA_KEY_DOWN            264
#define MISAKA_KEY_UP              265
#define MISAKA_KEY_PAGE_UP         266
#define MISAKA_KEY_PAGE_DOWN       267
#define MISAKA_KEY_HOME            268
#define MISAKA_KEY_END             269
#define MISAKA_KEY_CAPS_LOCK       280
#define MISAKA_KEY_SCROLL_LOCK     281
#define MISAKA_KEY_NUM_LOCK        282
#define MISAKA_KEY_PRINT_SCREEN    283
#define MISAKA_KEY_PAUSE           284
#define MISAKA_KEY_F1              290
#define MISAKA_KEY_F2              291
#define MISAKA_KEY_F3              292
#define MISAKA_KEY_F4              293
#define MISAKA_KEY_F5              294
#define MISAKA_KEY_F6              295
#define MISAKA_KEY_F7              296
#define MISAKA_KEY_F8              297
#define MISAKA_KEY_F9              298
#define MISAKA_KEY_F10             299
#define MISAKA_KEY_F11             300
#define MISAKA_KEY_F12             301
#define MISAKA_KEY_F13             302
#define MISAKA_KEY_F14             303
#define MISAKA_KEY_F15             304
#define MISAKA_KEY_F16             305
#define MISAKA_KEY_F17             306
#define MISAKA_KEY_F18             307
#define MISAKA_KEY_F19             308
#define MISAKA_KEY_F20             309
#define MISAKA_KEY_F21             310
#define MISAKA_KEY_F22             311
#define MISAKA_KEY_F23             312
#define MISAKA_KEY_F24             313
#define MISAKA_KEY_F25             314
#define MISAKA_KEY_KP_0            320
#define MISAKA_KEY_KP_1            321
#define MISAKA_KEY_KP_2            322
#define MISAKA_KEY_KP_3            323
#define MISAKA_KEY_KP_4            324
#define MISAKA_KEY_KP_5            325
#define MISAKA_KEY_KP_6            326
#define MISAKA_KEY_KP_7            327
#define MISAKA_KEY_KP_8            328
#define MISAKA_KEY_KP_9            329
#define MISAKA_KEY_KP_DECIMAL      330
#define MISAKA_KEY_KP_DIVIDE       331
#define MISAKA_KEY_KP_MULTIPLY     332
#define MISAKA_KEY_KP_SUBTRACT     333
#define MISAKA_KEY_KP_ADD          334
#define MISAKA_KEY_KP_ENTER        335
#define MISAKA_KEY_KP_EQUAL        336
#define MISAKA_KEY_LEFT_SHIFT      340
#define MISAKA_KEY_LEFT_CONTROL    341
#define MISAKA_KEY_LEFT_ALT        342
#define MISAKA_KEY_LEFT_SUPER      343
#define MISAKA_KEY_RIGHT_SHIFT     344
#define MISAKA_KEY_RIGHT_CONTROL   345
#define MISAKA_KEY_RIGHT_ALT       346
#define MISAKA_KEY_RIGHT_SUPER     347
#define MISAKA_KEY_MENU            348

#endif